blog/urls.py
from django.urls import path

from . import views

app_name = "weblog"
urlpatterns = [
    path(
        "<int:year>/<str:month>/<int:day>/<slug>/",
        views.BlogDateDetailView.as_view(),
        name="entry",
    ),
    path(
        "<int:year>/<str:month>/<int:day>/",
        views.BlogDayArchiveView.as_view(),
        name="archive-day",
    ),
    path(
        "<int:year>/<str:month>/",
        views.BlogMonthArchiveView.as_view(),
        name="archive-month",
    ),
    path("<int:year>/", views.BlogYearArchiveView.as_view(), name="archive-year"),
    path("", views.BlogArchiveIndexView.as_view(), name="index"),
]

docs/urls.py
from django.urls import path, re_path
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    path("", views.index, name="homepage"),
    path("search/", views.redirect_search),
    path("<lang>/", views.language),
    re_path(
        r"^[a-z-]+/[\w.-]+/internals/team/$",
        RedirectView.as_view(
            url="https://www.djangoproject.com/foundation/teams/",
            permanent=True,
        ),
    ),
    re_path("^(?P<lang>[a-z-]+)/(?P<version>stable)/(?P<url>.*)$", views.stable),
    re_path(
        r"^(?P<lang>[a-z-]+)/(?P<version>[\w.-]+)/$",
        views.document,
        {"url": ""},
        name="document-index",
    ),
    re_path(
        r"^(?P<lang>[a-z-]+)/(?P<version>[\w.-]+)/_objects/$",
        views.objects_inventory,
        name="objects-inv",
    ),
    re_path(
        r"^(?P<lang>[a-z-]+)/(?P<version>[\w.-]+)/_images/(?P<path>.*)$",
        views.sphinx_static,
        {"subpath": "_images"},
        name="sphinx-images",
    ),
    re_path(
        r"^(?P<lang>[a-z-]+)/(?P<version>[\w.-]+)/_source/(?P<path>.*)$",
        views.sphinx_static,
        {"subpath": "_sources"},
        name="sphinx-sources",
    ),
    re_path(
        r"^(?P<lang>[a-z-]+)/(?P<version>[\w.-]+)/_downloads/(?P<path>.*)$",
        views.sphinx_static,
        {"subpath": "_downloads"},
        name="sphinx-downloads",
    ),
    re_path("^(.*)/index/$", views.redirect_index),
    re_path(
        r"^(?P<lang>[a-z-]+)/(?P<version>[\w.-]+)/search/$",
        views.search_results,
        name="document-search",
    ),
    re_path(
        r"^(?P<lang>[a-z-]+)/(?P<version>[\w.-]+)/search/description/$",
        views.search_description,
        name="document-search-description",
    ),
    re_path(
        r"^(?P<lang>[a-z-]+)/(?P<version>[\w.-]+)/search/suggestions/$",
        views.search_suggestions,
        name="document-search-suggestions",
    ),
    re_path(
        r"^(?P<lang>[a-z-]+)/(?P<version>[\w.-]+)/(?P<url>[\w./-]*)/$",
        views.document,
        name="document-detail",
    ),
    re_path(r"^pots/(?P<pot_name>\w+\.pot)$", views.pot_file),
]

docs/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

search_placeholder = _("Search %s documentation")


class DocSearchForm(forms.Form):
    q = forms.CharField(required=False, label=_("Search"))

    def __init__(self, data=None, **kwargs):
        self.release = kwargs.pop("release")
        super().__init__(data=data, **kwargs)
        self.fields["q"].widget = forms.TextInput(
            attrs={
                "type": "search",
                "placeholder": search_placeholder % self.release.human_version,
            }
        )

docs/views.py
import datetime
import json

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.contrib.sitemaps.views import x_robots_tag
from django.contrib.sites.models import Site
from django.core.paginator import InvalidPage, Paginator
from django.http import Http404, JsonResponse
from django.shortcuts import redirect, render
from django.template.response import TemplateResponse
from django.utils.translation import activate, gettext_lazy as _
from django.views import static
from django.views.decorators.cache import cache_page
from django_hosts.resolvers import reverse

from .forms import DocSearchForm
from .models import Document, DocumentRelease
from .utils import get_doc_path_or_404, get_doc_root_or_404

SIMPLE_SEARCH_OPERATORS = ["+", "|", "-", '"', "*", "(", ")", "~"]


def index(request):
    return redirect(DocumentRelease.objects.current())


def language(request, lang):
    return redirect(DocumentRelease.objects.current(lang))


def stable(request, lang, version, url):
    path = request.get_full_path()
    current_version = DocumentRelease.objects.current_version()
    return redirect(path.replace(version, current_version, 1))


def document(request, lang, version, url):
    # If either of these can't be encoded as ascii then later on down the line an
    # exception will be emitted by unipath, proactively check for bad data (mostly
    # from the Googlebot) so we can give a nice 404 error.
    try:
        lang.encode("ascii")
        version.encode("ascii")
        url.encode("ascii")
    except UnicodeEncodeError:
        raise Http404

    activate(lang)

    canonical_version = DocumentRelease.objects.current_version()
    canonical = version == canonical_version
    if version == "stable":
        version = canonical_version

    docroot = get_doc_root_or_404(lang, version)
    doc_path = get_doc_path_or_404(docroot, url)
    try:
        release = DocumentRelease.objects.get_by_version_and_lang(version, lang)
    except DocumentRelease.DoesNotExist:
        raise Http404

    if version == "dev":
        rtd_version = "latest"
    else:
        rtd_version = version + ".x"

    template_names = [
        "docs/%s.html"
        % str(doc_path.relative_to(docroot)).replace(str(doc_path.suffix), ""),
        "docs/doc.html",
    ]

    def load_json_file(path):
        with path.open("r") as f:
            return json.load(f)

    available_languages = DocumentRelease.objects.get_available_languages_by_version(
        version
    )

    context = {
        "doc": load_json_file(doc_path),
        "env": load_json_file(docroot.joinpath("globalcontext.json")),
        "lang": lang,
        "version": version,
        "canonical_version": canonical_version,
        "canonical": canonical,
        "available_languages": available_languages,
        "release": release,
        "rtd_version": rtd_version,
        "docurl": url,
        "update_date": datetime.datetime.fromtimestamp(
            (docroot.joinpath("last_build")).stat().st_mtime
        ),
        "redirect_from": request.GET.get("from", None),
    }
    response = render(request, template_names, context)
    # Tell Fastly to re-fetch from the origin once a week
    # (we'll invalidate the cache sooner if needed)
    response["Surrogate-Control"] = "max-age=%d" % (7 * 24 * 60 * 60)
    return response


if not settings.DEBUG:
    # Specify a dedicated cache for docs pages that need to be purged after
    # docs rebuilds (see docs/management/commands/update_docs.py):
    document = cache_page(settings.CACHE_MIDDLEWARE_SECONDS, cache="docs-pages")(
        document
    )


def pot_file(request, pot_name):
    version = DocumentRelease.objects.current().version
    doc_root = str(get_doc_root_or_404("en", version, subroot="gettext"))
    return static.serve(request, document_root=doc_root, path=pot_name)


def sphinx_static(request, lang, version, path, subpath=None):
    """
    Serve Sphinx static assets from a subdir of the build location.
    """
    document_root = str(get_doc_root_or_404(lang, version).joinpath(subpath))
    return static.serve(request, document_root=document_root, path=path)


def objects_inventory(request, lang, version):
    response = static.serve(
        request,
        document_root=str(get_doc_root_or_404(lang, version)),
        path="objects.inv",
    )
    response["Content-Type"] = "text/plain"
    return response


def redirect_index(request, *args, **kwargs):
    assert request.path.endswith("index/")
    return redirect(request.path[:-6])


def redirect_search(request):
    """
    Legacy search view to handle old queries correctly, e.g. in scraping
    sites, command line interface etc.
    """
    release = DocumentRelease.objects.current()
    kwargs = {
        "lang": release.lang,
        "version": release.version,
    }
    search_url = reverse("document-search", host="docs", kwargs=kwargs)
    q = request.GET.get("q") or None
    if q:
        search_url += "?q=%s" % q
    return redirect(search_url)


def search_results(request, lang, version, per_page=10, orphans=3):
    """
    Search view to handle language and version specific queries.
    The old search view is being redirected here.
    """
    try:
        release = DocumentRelease.objects.get_by_version_and_lang(version, lang)
    except DocumentRelease.DoesNotExist:
        raise Http404

    activate(lang)

    form = DocSearchForm(request.GET or None, release=release)

    context = {
        "form": form,
        "lang": release.lang,
        "version": release.version,
        "release": release,
        "searchparams": request.GET.urlencode(),
    }

    if form.is_valid():
        q = form.cleaned_data.get("q")

        if q:
            # catch queries that are coming from browser search bars
            exact = Document.objects.filter(release=release, title=q).first()
            if exact is not None:
                return redirect(exact)

            results = Document.objects.search(q, release)

            page_number = request.GET.get("page") or 1
            paginator = Paginator(results, per_page=per_page, orphans=orphans)

            try:
                page_number = int(page_number)
            except ValueError:
                if page_number == "last":
                    page_number = paginator.num_pages
                else:
                    raise Http404(
                        _("Page is not 'last', " "nor can it be converted to an int.")
                    )

            try:
                page = paginator.page(page_number)
            except InvalidPage as e:
                raise Http404(
                    _("Invalid page (%(page_number)s): %(message)s")
                    % {"page_number": page_number, "message": str(e)}
                )

            context.update(
                {
                    "query": q,
                    "page": page,
                    "paginator": paginator,
                }
            )

    return render(request, "docs/search_results.html", context)


def search_suggestions(request, lang, version, per_page=20):
    """
    The endpoint for the OpenSearch browser integration.

    This will do a simple prefix match against the title to catch
    documents with a meaningful title.

    The link list contains redirect URLs so that IE will correctly
    redirect to those documents.
    """
    try:
        release = DocumentRelease.objects.get_by_version_and_lang(version, lang)
    except DocumentRelease.DoesNotExist:
        raise Http404

    activate(lang)

    form = DocSearchForm(request.GET or None, release=release)
    suggestions = []

    if form.is_valid():
        q = form.cleaned_data.get("q")
        if q:
            results = (
                Document.objects.filter(
                    release__lang=release.lang,
                )
                .filter(
                    release__release__version=release.version,
                )
                .filter(
                    title__contains=q,
                )
            )
            suggestions.append(q)
            titles = []
            links = []
            content_type = ContentType.objects.get_for_model(Document)
            for result in results:
                titles.append(result.title)
                kwargs = {
                    "content_type_id": content_type.pk,
                    "object_id": result.id,
                }
                links.append(reverse("contenttypes-shortcut", kwargs=kwargs))
            suggestions.append(titles)
            suggestions.append([])
            suggestions.append(links)

    return JsonResponse(suggestions, safe=False)


if not settings.DEBUG:
    # 1 hour to handle the many requests
    search_suggestions = cache_page(60 * 60)(search_suggestions)


def search_description(request, lang, version):
    """
    Render an OpenSearch description.
    """
    try:
        release = DocumentRelease.objects.get_by_version_and_lang(version, lang)
    except DocumentRelease.DoesNotExist:
        raise Http404

    activate(lang)

    context = {
        "site": Site.objects.get_current(),
        "release": release,
    }
    return render(
        request,
        "docs/search_description.xml",
        context,
        content_type="application/opensearchdescription+xml",
    )


if not settings.DEBUG:
    # 1 week because there is no need to render it more often
    search_description = cache_page(60 * 60 * 24 * 7)(search_description)


@x_robots_tag
def sitemap_index(request, sitemaps):
    """
    Simplified version of django.contrib.sitemaps.views.index that uses
    django_hosts for URL reversing.
    """
    sites = []
    for section in sitemaps.keys():
        sitemap_url = reverse(
            "document-sitemap", host="docs", kwargs={"section": section}
        )
        sites.append(sitemap_url)
    return TemplateResponse(
        request,
        "sitemap_index.xml",

docs/templates/docs/doc.html
{% extends "base_docs.html" %}
{% load i18n fundraising_extras docs %}

{% block title %}{{ doc.title|striptags|safe }} | {% trans "Django documentation" %}{% endblock %}

{% block doc_url %}{% url 'document-index' lang=lang version=version host 'docs' %}{% endblock %}

{% block link_rel_tags %}
  {% if docurl %}
    {% if "internals" in docurl and lang == "en" %} {# The canonical version of "internals" is the dev docs (but only for English, since the dev docs are never translated). #}
      {% url 'document-detail' lang=lang version='dev' url=docurl host 'docs' as canonical_url %}
    {% else %}
      {% url 'document-detail' lang=lang version=canonical_version url=docurl host 'docs' as canonical_url %}
    {% endif %}
  {% else %}
    {% url 'document-index' lang=lang version=canonical_version host 'docs' as canonical_url %}
  {% endif %}
  <link rel="canonical" href="{{ canonical_url }}">
  {% for available_lang in available_languages %}
    {% if docurl %}
      {% url 'document-detail' lang=available_lang version=version url=docurl host 'docs' as alternate_url %}
    {% else %}
      {% url 'document-index' lang=available_lang version=version host 'docs' as alternate_url %}
    {% endif %}
    <link rel="alternate"
          hreflang="{{ available_lang }}"
          href="{{ alternate_url }}">
  {% endfor %}

  <link rel="search"
        type="application/opensearchdescription+xml"
        href="{% url 'document-search-description' lang=lang version=version host 'docs' %}"
        title="{% trans "Django documentation" %}">
{% endblock link_rel_tags %}

{% block body_extra %}
  {% if release.is_dev %}
    {% if "internals" not in docurl %}{# The dev version is canonical for internals/. #}
      <div id="dev-warning" class="doc-floating-warning">
        {% trans "This document is for Django's development version, which can be significantly different from previous releases. For older releases, use the version selector floating in the bottom right corner of this page." %}
      </div>
    {% endif %}
  {% elif release.is_preview %}
    <div id="dev-warning" class="doc-floating-warning">
      {% trans "This document is for a preview release of Django, which can be significantly different from previous releases. For older releases, use the version selector floating in the bottom right corner of this page." %}
    </div>
  {% elif not release.is_supported %}
    <div id="outdated-warning" class="doc-floating-warning">
      {% trans "This document is for an insecure version of Django that is no longer supported. Please upgrade to a newer release!" %}
    </div>
  {% endif %}
{% endblock body_extra %}

{% block content %}
  <div id="version-switcher">
    <ul id="faq-link">
      <li class="current-link">
        <a href="{% url 'document-detail' lang=lang version=version url='faq/help' host 'docs' %}">
          <span>{% trans "Getting Help" %}</span>
        </a>
      </li>
    </ul>
    <ul id="doc-languages" class="language-switcher doc-switcher">
      {% for available_lang in available_languages %}
        {% if lang != available_lang %}
          <li class="other">
            {% if docurl %}
              {% url 'document-detail' lang=available_lang version=version url=docurl host 'docs' as other_url %}
            {% else %}
              {% url 'document-index' lang=available_lang version=version host 'docs' as other_url %}
            {% endif %}
            <a href="{{ other_url }}{% if searchparams %}search/?{{ searchparams }}{% endif %}">{{ available_lang }}</a>
          </li>
        {% endif %}
      {% endfor %}
      <li class="current"
          title="{% blocktrans %}Click on the links on the left to switch to another language.{% endblocktrans %}">
        <span>{% trans "Language:" %} <strong>{{ lang }}</strong></span>
      </li>
    </ul>

    {% get_all_doc_versions docurl as other_versions %}
    <ul id="doc-versions" class="version-switcher doc-switcher">
      {% for other_version in other_versions %}
        {% if version != other_version %}
          <li class="other">
            {% if docurl %}
              {% url 'document-detail' lang=lang version=other_version url=docurl host 'docs' as other_url %}
            {% else %}
              {% url 'document-index' lang=lang version=other_version host 'docs' as other_url %}
            {% endif %}
            <a href="{{ other_url }}{% if searchparams %}search/?{{ searchparams }}{% endif %}">{{ other_version }}</a>
          </li>
        {% endif %}
      {% endfor %}
      <li class="current{% if release.is_dev %} dev{% endif %}"
          title="{% if release.is_dev %}{% blocktrans trimmed %}
                   This document is for Django's development version, which can be significantly different from previous releases.
                 {% endblocktrans %}{% else %}{% blocktrans trimmed %}
                   This document describes Django {{ version }}.
                 {% endblocktrans %}{% endif %} {% blocktrans trimmed %}
                   Click on the links on the left to see other versions.
                 {% endblocktrans %}">
        <span>{% trans "Documentation version:" %}
          <strong>{% if release.is_dev %}development{% else %}{{ version }}{% endif %}</strong>
        </span>
      </li>
    </ul>
    <ul id="backtotop-link">
      <li class="current-link">
        <a href="#top" aria-label="Back to top" class="icon-chevron-up-align"><i class="icon icon-chevron-up"></i></a>
      </li>
    </ul>
  </div>

  {% block body %}
    <div id="docs-content">
      {{ doc.body|safe }}
    </div>
  {% endblock body %}

  {% if doc.prev or doc.next %}
    <div class="browse-horizontal">
      {% if doc.prev %}
        <div class="left"><a href="{{ doc.prev.link }}"><i class="icon icon-chevron-left"></i> {{ doc.prev.title|safe }}</a></div>
      {% endif %}
      {% if doc.next %}
        <div class="right"><a href="{{ doc.next.link }}">{{ doc.next.title|safe }} <i class="icon icon-chevron-right"></i></a></div>
      {% endif %}
    </div>
  {% endif %}

{% endblock content %}


{% block content-related %}
  <h1 class="visuallyhidden">{% trans "Additional Information" %}</h1>
  <div role="complementary">

    {% donation_snippet %}

    {% block toc-wrapper %}
      <h2>{% trans "Contents" %}</h2>
      {% block toc %}
        {{ doc.toc|safe }}
      {% endblock toc %}
    {% endblock toc-wrapper %}

    {% block browse-wrapper %}
      <h2>{% trans "Browse" %}</h2>
      <ul>
        {% block browse %}
          {% if doc.prev %}
            <li>{% trans "Prev:" %} <a href="{{ doc.prev.link }}">{{ doc.prev.title|safe }}</a></li>
          {% endif %}
          {% if doc.next %}
            <li>{% trans "Next:" %} <a href="{{ doc.next.link }}">{{ doc.next.title|safe }}</a></li>
          {% endif %}
          <li><a href="{% url 'document-detail' lang=lang version=version url="contents" host 'docs' %}">{% trans "Table of contents" %}</a></li>
          {% for doc, title, accesskey, shorttitle in env.rellinks %}
            <li><a href="{% url 'document-detail' lang=lang version=version url=doc host 'docs' %}">{{ title }}</a></li>
          {% endfor %}
        {% endblock browse %}
      </ul>
    {% endblock browse-wrapper %}

    {% block breadcrumbs-wrapper %}
      <h2>{% trans "You are here:" %}</h2>
      <ul>
        <li>
          <a href="{% url 'document-index' lang=lang version=version host 'docs' %}">{% blocktrans %}Django {{ version }} documentation{% endblocktrans %}</a>
          {% for p in doc.parents %}
            <ul><li><a href="{{ p.link }}">{{ p.title|safe }}</a>
          {% endfor %}
          <ul><li>{% block current-page-title %}{{ doc.title|safe }}{% endblock current-page-title %}</li></ul>
          {% for p in doc.parents %}</li></ul>{% endfor %}
        </li>
      </ul>
    {% endblock breadcrumbs-wrapper %}

    {% block help-wrapper %}
      <h2 id="getting-help-sidebar">{% trans "Getting help" %}</h2>
      <dl class="list-links">
        <dt><a href="{% url 'document-detail' lang=lang version=version url="faq" host 'docs' %}">{% trans "FAQ" %}</a></dt>
        <dd>{% blocktrans %}Try the FAQ — it's got answers to many common questions.{% endblocktrans %}</dd>

        <dt><a href="/en/stable/genindex/">{% trans "Index" %}</a>, <a href="/en/stable/py-modindex/">{% trans "Module Index" %}</a>, or <a href="/en/stable/contents/">{% trans "Table of Contents" %}</a></dt>
        <dd>{% blocktrans %}Handy when looking for specific information.{% endblocktrans %}</dd>

        <dt><a href="https://groups.google.com/group/django-users/">{% trans "django-users mailing list" %}</a></dt>
        <dd>{% blocktrans %}Search for information in the archives of the django-users mailing list, or post a question.{% endblocktrans %}</dd>

        <dt><a href="irc://irc.libera.chat/django">{% trans "#django IRC channel" %}</a></dt>
        <dd>{% blocktrans %}Ask a question in the #django IRC channel, or search the IRC logs to see if it’s been asked before.{% endblocktrans %}</dd>

        <dt><a href="https://discord.gg/xcRH6mN4fa">{% trans "Django Discord Server" %}</a></dt>
        <dd>{% blocktrans %}Join the Django Discord Community.{% endblocktrans %}</dd>

        <dt><a href="https://forum.djangoproject.com/">{% trans "Official Django Forum" %}</a></dt>
        <dd>{% blocktrans %}Join the community on the Django Forum.{% endblocktrans %}</dd>

        <dt><a href="https://code.djangoproject.com/">{% trans "Ticket tracker" %}</a></dt>
        <dd>{% blocktrans %}Report bugs with Django or Django documentation in our ticket tracker.{% endblocktrans %}</dd>
      </dl>
    {% endblock help-wrapper %}

    {% block links-wrapper %}
      <h2>{% trans "Download:" %}</h2>
      <p>
        {% if version == "dev" %}{% trans "Offline (development version):" %}
        {% else %}{% blocktrans %}Offline (Django {{ version }}):{% endblocktrans %}{% endif %}
        <a href="{{ MEDIA_URL }}docs/django-docs-{{ version }}-{{ lang }}.zip">HTML</a> |
        <a href="https://media.readthedocs.org/pdf/django/{{ rtd_version }}/django.pdf">PDF</a> |
        <a href="https://media.readthedocs.org/epub/django/{{ rtd_version }}/django.epub">ePub</a>
        <br>
        <span class="quiet">
          {% blocktrans %}Provided by <a href="https://readthedocs.org/">Read the Docs</a>.{% endblocktrans %}
        </span>
      </p>
    {% endblock links-wrapper %}
  </div>
{% endblock content-related %}

docs/templates/docs/genindex.html
{% extends "docs/doc.html" %}
{% load i18n %}

{% block title %}{% trans "General Index | Django Documentation" %}{% endblock %}
{% block toc-wrapper %}{% endblock %}
{% block current-page-title %}{% trans "General Index" %}{% endblock %}

{% block body %}
  <h1>{% trans "General Index" %}</h1>

  <p class="indexletters">
    {% for letter, _ in doc.genindexentries %}
      <a href="#{{ letter }}">{{ letter }}</a> {% if not forloop.last %} |{% endif %}
    {% endfor %}
  </p>


  {% for letter, entries in doc.genindexentries %}
    <br/ ><hr />

    <h2 id="{{ letter }}">{{ letter }}</h2>

    <dl class="index">
      {% for name, contents in entries %}
        <dt>
          {# contents.0 is a list of links for the item #}
          {% if contents.0 %}
            <a href="{{ contents.0.0.1 }}">{{ name }}</a>
          {% else %}
            {{ name }}
          {% endif %}
        </dt>

        {# contents.1 is a list of subitems #}
        {% if contents.1 %}
          {% for subname, sublinks in contents.1 %}
            <dd>
              <a href="{{ sublinks.0.1 }}">{{ subname }}</a>
              {% for link in sublinks|slice:"1:" %}, <a href="{{ link.1 }}">{% trans "[Link]" %}</a>{% endfor %}
            </dd>
          {% endfor %}
        {% endif %}
      {% endfor %}
    </dl>
  {% endfor %}
{% endblock %}

docs/templates/docs/index.html
{% extends "docs/doc.html" %}

{% block toc-wrapper %}{% endblock %}

docs/templates/docs/py-modindex.html
{% extends "docs/doc.html" %}
{% load i18n %}

{% block title %}{% trans "Module Index | Django Documentation" %}{% endblock %}
{% block toc-wrapper %}{% endblock %}
{% block current-page-title %}{% trans "Module Index" %}{% endblock %}

{% block body %}
    <h1>{% trans "Module Index" %}</h1>

    <ul class="jump_links">
        {% for letter, objects in doc.content %}
            <a href="#{{ letter }}"><strong>{{ letter }}</strong></a>{% if not forloop.last %} | {% endif %}
        {% endfor %}
    </ul>

    {% for letter, objects in doc.content %}
        <h3><a name="{{ letter }}">{{ letter|upper }}</a></h3>
        <ul>
            {% for module_name, subtype, docname, path, platforms, qualifier, synopsis in objects %}
                {% if docname %}
                    <li>
                        <a href="../{{ docname }}"><tt class="literal xref">{{ module_name }}</tt></a>
                        {% if synopsis %}
                            <span class="synopsis"><br />{{ synopsis }}</span>
                        {% endif %}
                    </li>
                {% endif %}

            {% endfor %}
        </ul>
    {% endfor %}

{% endblock %}

docs/templates/docs/search_form.html
{% load i18n %}

<form action="{% url 'document-search' version=version lang=lang host 'docs' %}" class="search form-input" role="search">
  <label class="visuallyhidden" for="id_q">Search:</label>
  {{ form.q }}

  <button type="submit">
    <i class="icon icon-search"></i>
    <span class="visuallyhidden">{% trans 'Search' %}</span>
  </button>
</form>

docs/templates/docs/search_results.html
{% extends "docs/doc.html" %}
{% load i18n docs %}

{% block title %}{% trans "Search | Django documentation" %}{% endblock %}

{% block toc-wrapper %}{% endblock %}
{% block breadcrumbs-wrapper %}{% endblock %}
{% block last-update-wrapper %}{% endblock %}
{% block browse-wrapper %}{% endblock %}
{% block links-wrapper %}{% endblock %}

{% block body %}
  {% if query %}
    <h2>
      {% if release.is_dev %}
        {% blocktrans count num_results=paginator.count trimmed %}
          Only 1 result for <em>{{ query }}</em> in the development version
        {% plural %}
          {{ num_results }} results for <em>{{ query }}</em> in the development version
        {% endblocktrans %}
      {% else %}
        {% blocktrans count num_results=paginator.count trimmed %}
          Only 1 result for <em>{{ query }}</em> in version {{ version }}
        {% plural %}
          {{ num_results }} results for <em>{{ query }}</em> in version {{ version }}
        {% endblocktrans %}
      {% endif %}
    </h2>
  {% else %}
    <h2>{% trans "No search query given" %}</h2>
  {% endif %}

  {% if query %}
    <div id="docs-content">
      <dl class="search-links">
        {% for result in page.object_list %}
          <dt>
            <h2 class="result-title">
              <a href="{% url 'document-detail' lang=result.release.lang version=result.release.version url=result.path host 'docs' %}">{{ result.headline|safe }}</a>
            </h2>
            <span class="meta breadcrumbs">
              {% for breadcrumb in result.breadcrumbs %}
                <a href="{% url 'document-detail' lang=result.release.lang version=result.release.version url=breadcrumb.path host 'docs' %}">{{ breadcrumb.title }}</a>{% if not forloop.last %} <span class="arrow">»</span>{% endif %}
              {% endfor %}
            </span>
          </dt>
          <dd>
            {% if result.highlight %}
              …&nbsp;{{ result.highlight|cut:"¶"|safe }}&nbsp;…
            {% endif %}
          </dd>
        {% endfor %}
      </dl>
    </div>

    {% if page.has_previous or page.has_next %}
      <div class="pagination">
        <ul class="nav-pagination" role="navigation">
          {% if page.has_previous %}
            <li><a class="previous" href="?q={{ query }}&amp;release={{ release.version }}&amp;page={{ page.previous_page_number }}">
              <i class="icon icon-chevron-left"></i>
              <span class="visuallyhidden">{% trans "Previous" %}</span>
            </a></li>
          {% endif %}
          <span class="page-current">
            {% blocktrans with page_number=page.number num_pages=page.paginator.num_pages trimmed %}
              Page {{ page_number }} of {{ num_pages }}
            {% endblocktrans %}
          </span>
          {% if page.has_next %}
            <li><a class="next" href="?q={{ query }}&amp;release={{ release.version }}&amp;page={{ page.next_page_number }}">
              <i class="icon icon-chevron-right"></i>
              <span class="visuallyhidden">{% trans "Next" %}</span>
            </a></li>
          {% endif %}
        </ul>
      </div>
    {% endif %}

  {% endif %}
{% endblock %}